### ISSUE TITLE
Nice idea, great package, but it misses a bunch of REMs

### ISSUE THREAD

**Issue by arxpoetica** [CedericPrivat/tailwindcss-base-font-size#1] opened 2023-07-10 01:33 UTC
For example, buttons are getting the right padding applied.

**Comment by CedericPrivat** [comment] 2023-07-12 11:48
> For example, buttons are getting the right padding applied.

Hey, thanks for your feedback!
Could you give me a minimal example of the issue you are having?

**Comment by arxpoetica** [comment] 2023-07-19 23:51
I kind of moved on from Tailwind all together (frustrated with its limitations), but I know padding on buttons was an issue.

**Comment by CedericPrivat** [comment] 2023-07-20 15:36
Tailwind doesn't really have specific classes for button paddings, only paddings in general. So if there's an issue with paddings, it would affect all of them.
Maybe if you have custom styles for buttons, that rely on `rem` units, they would change, since the base font size changes.

Since I can't really reproduce the issue, I will close it for now.

Feel free to reopen if you have new insights.

**Closed** 2023-07-20 15:36 UTC
